//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TextEdit.rc
//
#define IDI_TEXTEDIT1                   1
#define IDI_TEXTEDIT2                   2
#define IDC_APPLY                       13
#define IDC_REPLACE                     14
#define IDC_CHANGE_FIXED_FONT           15
#define IDC_BROWSE                      16
#define IDC_REPLACE_ALL                 17
#define IDC_CHANGE_PROPORTIONAL_FONT    18
#define IDC_BROWSEDOCPATH               19
#define IDR_MENU                        101
#define IDR_ACCELERATOR                 102
#define IDD_PROPERTIES                  105
#define IDD_FILENOTFOUND                107
#define IDD_EDITFIND                    108
#define IDI_FIND                        109
#define IDR_MRU                         110
#define IDD_OPTIONS                     111
#define IDD_ABOUT                       114
#define IDR_COMMANDS                    118
#define IDR_TOOLBAR                     121
#define IDR_TOOLBAR_LARGE               126
#define IDD_DIALOG_WITH_CHILD_IDS       128
#define IDD_SETUP                       129
#define IDD_DELETE                      130
#define IDI_WASTEBASKET                 131
#define IDI_DELETE                      132
#define IDD_INSTALL_1                   135
#define IDR_CNT_FILE                    137
#define IDR_HLP_FILE                    138
#define IDI_WASTEBASKETEMPTY            139
#define IDI_SETUP                       144
#define IDI_ARROW_UP                    145
#define IDI_ARROW_DOWN                  146
#define IDD_PAGE_SETUP                  147
#define IDD_PRINT                       148
#define IDD_PRINT_SETUP                 149
#define IDI_FIXED_FONT                  151
#define IDI_PROPORTIONAL_FONT           152
#define IDD_FONT                        153
#define IDD_SAVE_CHILD                  159
#define IDI_MS_DOS                      162
#define IDI_PROG_FOLDER                 166
#define IDI_TEXTEDIT                    169
#define ID_COMMAND_ID                   170
#define ID_SENDTO_SYSTEM                171
#define IDD_PREVIEW_CHILD               195
#define IDD_EDITREPLACE                 196
#define IDD_MOVE_CHILD                  197
#define IDD_DELETE_STDIN                198
#define IDD_COPY_CHILD                  199
#define IDC_FILENAME                    1000
#define IDC_UNICODE                     1001
#define IDC_UNIXLINEFEEDS               1004
#define IDC_BROWSEPATH                  1006
#define IDC_TOOLBAR                     1006
#define IDC_PATH                        1007
#define IDC_STATUSBAR                   1007
#define IDC_TABLABEL                    1008
#define IDC_READ_ONLY                   1008
#define IDC_TABEDIT                     1009
#define IDC_ARCHIVE                     1009
#define IDC_TABUPDOWN                   1010
#define IDC_COMPRESSED                  1010
#define IDC_READONLY                    1011
#define IDC_HIDDEN                      1011
#define IDC_EDIT                        1012
#define IDC_SYSTEM                      1012
#define IDC_FILETYPE                    1015
#define IDC_FILESIZE                    1016
#define IDC_COMPRESSEDFILESIZE          1017
#define IDC_MODIFIED                    1018
#define IDC_ACCESSED                    1019
#define IDC_MSDOS_NAME                  1020
#define IDC_CREATED                     1021
#define IDC_PREVIEW                     1024
#define IDC_MESSAGE                     1026
#define IDC_SEARCHPATTERN               1027
#define IDC_MESSAGE2                    1027
#define IDC_MATCH_WHOLE_WORD            1028
#define IDC_MATCH_CASE                  1029
#define IDC_UP                          1030
#define IDC_DOWN                        1031
#define IDC_REPLACEMENT                 1032
#define IDC_TITLE                       1035
#define IDC_VERSION                     1036
#define IDC_COPYRIGHT                   1037
#define IDC_COMMERCIAL                  1038
#define IDC_COMMENTS                    1039
#define IDC_SEARCH_TIP                  1043
#define IDC_FILEICON                    1047
#define IDC_TRASHCAN                    1049
#define IDC_INFO                        1050
#define IDC_SETUP_TITLE                 1051
#define IDC_SHOWDELETEDIALOG            1051
#define IDC_SHOWDELETEDIALOG2           1052
#define IDC_SETUP_ICON                  1053
#define IDC_INSTALL                     1054
#define IDC_UNINSTALL                   1055
#define IDC_PROGRESS                    1056
#define IDC_CUSTOMIZE                   1057
#define IDC_FILETYPES                   1058
#define IDC_ANIMATE                     1059
#define IDC_TIP                         1060
#define IDC_WASTEBASKET                 1062
#define IDC_WASTEBASKETEMPTY            1063
#define IDC_ARROW_DOWN                  1065
#define IDC_ARROW_UP                    1066
#define IDC_SELECTION                   1067
#define IDC_WHOLE_FILE                  1068
#define IDC_FIXED_FONT_SAMPLE           1069
#define IDC_PROPORTIONAL_FONT_SAMPLE    1070
#define IDC_EDIT1                       1070
#define IDC_LANGUAGE                    1071
#define IDC_LANGUAGE_LABEL              1072
#define IDC_DOC_PATH                    1074
#define IDC_NEW_WINDOW                  1075
#define ID_FILE_NEW                     40006
#define ID_FILE_OPEN                    40007
#define ID_FILE_CLOSE                   40008
#define ID_FILE_PRINT                   40009
#define ID_EDIT_UNDO                    40010
#define ID_EDIT_REDO                    40011
#define ID_EDIT_CUT                     40012
#define ID_EDIT_COPY                    40013
#define ID_EDIT_PASTE                   40014
#define ID_EDIT_DELETE                  40015
#define ID_HELP_ABOUT                   40016
#define ID_EDIT_FINDNEXT                40017
#define ID_EDIT_REPLACE                 40018
#define ID_EDIT_SELECTALL               40019
#define ID_FILE_ABANDONCHANGES          40020
#define ID_FILE_PROPERTIES              40021
#define IDS_SAVED_FILE                  40022
#define ID_EDIT_FIND                    40023
#define ID_VIEW_TOOLBAR                 40024
#define ID_VIEW_STATUSBAR               40025
#define ID_INSERT_DATEANDTIME           40026
#define IDS_INSTALL_SEARCH              40026
#define IDS_DIDNT_SAVE_FILE             40027
#define ID_FILE_PAGESETUP               40028
#define ID_VIEW_WORDWRAP                40029
#define ID_VIEW_OPTIONS                 40030
#define ID_INSERT_FILE                  40031
#define IDS_INSTALL_FOUND               40031
#define IDS_FILE_COPY                   40032
#define ID_EDIT_FINDSELECTION           40033
#define ID_MRU_1                        40034
#define ID_MRU_2                        40035
#define IDS_INSTALL_NOT_FOUND           40035
#define ID_MRU_3                        40036
#define IDS_INSTALL                     40036
#define ID_MRU_4                        40037
#define IDS_INSTALL_UNINSTALL           40037
#define ID_MRU_5                        40038
#define IDS_DELETING                    40038
#define ID_MRU_6                        40039
#define IDS_DELETED                     40039
#define ID_MRU_7                        40040
#define IDS_DELAYED_REMOVE              40040
#define ID_MRU_8                        40041
#define IDS_INSTALL_COPYING             40041
#define ID_MRU_9                        40042
#define IDS_INSTALL_SUCCESS             40042
#define ID_MRU_10                       40043
#define IDS_UNINSTALL_HINT              40043
#define IDS_WRONG_COMCTL32_VERSION      40044
#define IDS_FATAL_ERROR                 40045
#define IDS_INIT_ERROR                  40046
#define IDS_ACCESS_DENIED               40047
#define IDS_OPENFILE                    40048
#define IDS_REPLACEMENTS                40049
#define IDS_REPLACEMENTS1               40050
#define IDS_CLOSE                       40051
#define IDS_OPENORCREATEFILE            40052
#define ID_HELP_CONTENTS                40053
#define ID_HELP_SEARCH                  40054
#define ID_HELP_INDEX                   40055
#define ID_VIEW_FIXEDFONT               40056
#define ID_VIEW_PROPORTIONALFONT        40057
#define ID_COMMAND_SAVE                 40058
#define IDS_INSTALL_FAILED              40058
#define ID_EDIT_UNDO_ARG                40059
#define ID_COMMAND_READONLY             40060
#define IDS_UNINSTALL_WARNING           40060
#define ID_EDIT_REDO_ARG                40061
#define ID_COMMAND_TABS                 40062
#define IDS_VERSION_WARNING             40062
#define IDS_FILE_NOT_COMPRESSED         40063
#define ID_COMMAND_DELETELINE           40064
#define IDS_FIND_FOLDER                 40064
#define IDS_BYTES                       40065
#define ID_COMMAND_SCROLLUP             40066
#define IDS_CHOOSE_FOLDER               40066
#define IDS_BYTES_USED                  40067
#define ID_COMMAND_SCROLLDOWN           40068
#define IDS_CHOOSE_DATA_FOLDER          40068
#define IDS_SAVEFILE                    40069
#define ID_EDIT_FINDPREVIOUS            40070
#define ID_EDIT_FINDNEXT_ARG            40071
#define ID_EDIT_FINDPREVIOUS_ARG        40072
#define ID_EDIT_FINDSELECTION_ARG       40073
#define ID_EDIT_FINDWORD                40074
#define ID_FILE_DELETE                  40075
#define ID_TABPLACEHOLDER               40076
#define IDS_EXTENSIONS                  40076
#define IDS_SETUP_SEARCHING             40077
#define IDS_READY                       40078
#define IDS_POSITION                    40079
#define IDS_PASSED_END_OF_FILE          40080
#define IDS_TAB_PROMPT                  40081
#define IDS_STRING_FOUND                40082
#define IDS_APP_TITLE                   40083
#define IDS_EDIT_WITH_TEXTEDIT          40084
#define ID_VIEW_SETPROPORTIONALFONT     40085
#define IDS_FILE_TYPE                   40085
#define IDS_ABOUT                       40086
#define ID_VIEW_SETFIXEDFONT            40087
#define IDS_UNDO                        40087
#define IDS_LOADING                     40088
#define IDS_FILE_NOT_FOUND              40089
#define IDS_UNKNOWN_OPTION              40090
#define ID_SET_TABS                     40091
#define IDS_REDO                        40091
#define IDS_STRING                      40092
#define ID_DEBUG_DIVIDEBYZERO           40093
#define IDS_UPGRADE_WARNING             40093
#define IDS_PASSED_START_OF_FILE        40094
#define ID_DEBUG_ACCESSVIOLATION        40095
#define IDS_COM_INIT_ERROR              40095
#define IDS_MOVE                        40096
#define ID_DEBUG_OUTOFMEMORY            40097
#define IDS_PRINT_ARG_ERROR             40097
#define IDS_REPLACETIP1                 40098
#define ID_DEBUG_STACKOVERFLOW          40099
#define IDS_CUSTOM                      40099
#define IDS_REPLACETIP2                 40100
#define ID_HELP_KEYBOARD                40101
#define IDS_BINARY                      40102
#define ID_FILE_COPY                    40103
#define IDS_ERR_SPACE                   40104
#define ID_VIEW_SETFONT                 40105
#define IDS_WILDCARDS                   40105
#define ID_EDIT_CUT_ARG                 40106
#define ID_ACCEL_FINDNEXT               40107
#define IDS_SAVE_EXCEPTION              40107
#define ID_EDIT_COPY_ARG                40108
#define ID_ACCEL_FINDPREVIOUS           40109
#define IDS_DEVICE_NOT_READY            40109
#define IDS_FAILED_MOVE                 40110
#define ID_ACCEL_FINDPREVSELECTION      40111
#define IDS_PRINT_HEADER                40112
#define ID_COMMAND_PROPSCHANGED         40113
#define ID_FILE_RENAME                  40114
#define ID_FILE_NEW_EDITOR              40115
#define ID_COMMAND_TOGGLEFONT           40116
#define ID_COMMAND_RESETSTATUSBAR       40117
#define ID_HELP_HOMEPAGE                40118
#define ID_FILE_SENDTO_MAILRECIPIENT    40119
#define ID_RELOAD                       40120
#define IDS_VERSION                     57645
#define IDS_TABS                        57646
#define IDS_STRING_NOT_FOUND            57647
#define IDS_NEW_FILE_1                  57648
#define IDS_NEW_FILE_N                  57649
#define IDS_TABS_LABEL                  57650
#define IDS_READ_ONLY                   57651
#define IDS_TABS_TIP                    57652
#define IDS_READ_ONLY_TIP               57653
#define IDS_TABS_UPDOWN_TIP             57654
#define IDS_FILEFILTERS                 57655
#define IDS_UNDO_TYPING                 57656
#define IDS_UNDO_DELETE                 57657
#define IDS_UNDO_DRAGDROP               57658
#define IDS_UNDO_CUT                    57659
#define IDS_UNDO_PASTE                  57660
#define IDS_FILE_MENU                   57661
#define IDS_EDIT_MENU                   57662
#define IDS_FIND_MENU                   57663
#define IDS_VIEW_MENU                   57664
#define IDS_HELP_MENU                   57665
#define IDS_SYSTEM_MENU                 57666
#define IDS_STDIN_1                     57667
#define IDS_STDIN_N                     57668
#define IDS_PROPERTIES_ERROR            57669
#define IDS_COPY_1                      57670
#define IDS_COPY_N                      57671
#define IDS_FILEFILTERS2                57672
#define IDS_COPY_FILE                   61729
#define IDS_FILE_SENDTO_MENU            61730
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         40122
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
